spring:
  application:
    name: user-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiaju
    username: root
    password: 123456

  messages:
    basename: i18n.login


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.wxit.glxt.model.domain



